apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yadage-lhcb-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yadage-lhcb-worker
    spec:
      containers:
       - name: yadage-lhcb-worker
         image: reanahub/reana-workflow-engine-yadage
         imagePullPolicy: Always
         env:
          - name: QUEUE_ENV
            value: yadage-lhcb-queue
          - name: EXPERIMENT
            value: lhcb
          - name: SHARED_VOLUME
            value: "/k8s/lhcb"
         volumeMounts:
          - name: lhcb
            mountPath: "/data"
      volumes:
       - name: lhcb
         cephfs:
           monitors:
            - 128.142.36.227:6790
            - 128.142.39.77:6790
            - 128.142.39.144:6790
           path: "/k8s/lhcb"
           user: k8s
           secretRef:
             name: ceph-secret
           readOnly: false

