apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: job-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: job-controller
    spec:
      containers:
       - name: job-controller
         image: gitlab-registry.cern.ch/rodrigdi/cap-reuse:reana-job-controller
         imagePullPolicy: Always
         ports:
          - containerPort: 5000
            name: "http"
         volumeMounts:
           - name: svaccount
             mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
      volumes:
       - name: svaccount
         secret:
           secretName: default-token-kul0l
