apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: message-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: message-broker
    spec:
      containers:
       - name: message-broker
         image: gitlab-registry.cern.ch/rodrigdi/cap-reuse:message-broker
         ports:
          - containerPort: 5672
            name: "tcp"
          - containerPort: 15672
            name: "management"
